<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>ru.smirnovjavadev</groupId>
  <artifactId>eskoder</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>eskoder</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>4.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>4.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.png</include>
          <include>**/*.xml</include>
          <include>**/*.css</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>ru.smirnovjavadev.Main</mainClass>
            </manifest>
            <manifestEntries>
              <Bundle-Icon>icon.png</Bundle-Icon>
              <Icon-Image>icon.png</Icon-Image>
            </manifestEntries>
          </archive>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
<!--      <plugin>-->
<!--        <groupId>com.akathist.maven.plugins.launch4j</groupId>-->
<!--        <artifactId>launch4j-maven-plugin</artifactId>-->
<!--        <version>1.7.25</version>-->
<!--        <executions>-->
<!--          <execution>-->
<!--            <id>l4j-clui</id>-->
<!--            <phase>package</phase>-->
<!--            <goals>-->
<!--              <goal>launch4j</goal>-->
<!--            </goals>-->
<!--          </execution>-->
<!--        </executions>-->
<!--        <configuration>-->
<!--          <outfile>eskoder.exe</outfile>-->
<!--          <jar>target/eskoder-1.0-SNAPSHOT-jar-with-dependencies.jar</jar>-->
<!--          <dontWrapJar>false</dontWrapJar>-->
<!--          <headerType>gui</headerType>-->
<!--          <classPath>-->
<!--            <mainClass>ru.smirnovjavadev.Main</mainClass>-->
<!--          </classPath>-->
<!--          <icon>C:/JDK/icon.ico</icon>-->
<!--          <jre>-->
<!--            &lt;!&ndash; Можно указать min/max версии Java &ndash;&gt;-->
<!--            <minVersion>1.8.0</minVersion>-->
<!--            &lt;!&ndash; Здесь путь можно оставить пустым, если не встраиваешь JRE &ndash;&gt;-->
<!--          </jre>-->
<!--        </configuration>-->
<!--      </plugin>-->
    </plugins>
  </build>
</project>